require('util')

log('- Info ------------------------------------------------')
log('./prototypes/nuclear/descriptions.lua')
log('-------------------------------------------------------')

apm.lib.utils.item.add.radioactive_description('apm_nuclear_yellowcake', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_002', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_007', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_012', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_017', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_022', 2)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_027', 2)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_032', 2)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_037', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_042', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_uranium_oxide_pellet_047', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_032', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_037', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_042', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_047', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_used_032', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_used_037', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_used_042', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_fuel_cell_used_047', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_plutonium_oxide_pellet', 2)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_plutonium_oxide_pellet_2', 3)
apm.lib.utils.item.add.radioactive_description('apm_fuel_cell_mox', 2)
apm.lib.utils.item.add.radioactive_description('apm_fuel_cell_mox_used', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_breeder_uranium_inventory', 1)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_breeder_uranium_inventory_enriched', 3)
apm.lib.utils.item.add.radioactive_description('apm_nuclear_radioactive_waste', 1)