data:extend{
    {
        type = "item",
        name = "struct-generic-scanner-settings",
        icon = "__aai-programmable-structures__/graphics/icon/settings.png",
        icon_size = 32,
        flags = { "hidden"},
        subgroup = "programmable-structures",
        order = "z[zone]",
        stack_size = 50,
        place_result = "struct-generic-scanner-settings",
    },
    {
        type = "item",
        name = "struct-generic-controller-settings",
        icon = "__aai-programmable-structures__/graphics/icon/settings.png",
        icon_size = 32,
        flags = { "hidden"},
        subgroup = "programmable-structures",
        order = "z[zone]",
        stack_size = 50,
        place_result = "struct-generic-controller-settings",
    },
    {
        type = "item",
        name = "struct-generic-input",
        icon = "__aai-programmable-structures__/graphics/icon/generic-input.png",
        icon_size = 32,
        flags = { "hidden"},
        subgroup = "programmable-structures",
        order = "z[zone]",
        stack_size = 50,
        place_result = "struct-generic-input",
    },
    {
        type = "item",
        name = "struct-generic-output",
        icon = "__aai-programmable-structures__/graphics/icon/generic-output.png",
        icon_size = 32,
        flags = { "hidden"},
        subgroup = "programmable-structures",
        order = "z[zone]",
        stack_size = 50,
        place_result = "struct-generic-output",
    },
    {
        type = "item",
        name = "zone-scan",
        icon = "__aai-programmable-structures__/graphics/icon/zone-scan.png",
        icon_size = 32,
        flags = {},
        subgroup = "programmable-structures",
        order = "b",
        stack_size = 50,
        place_result = "zone-scan",
    },
    {
        type = "item",
        name = "zone-control",
        icon = "__aai-programmable-structures__/graphics/icon/zone-control.png",
        icon_size = 32,
        flags = {},
        subgroup = "programmable-structures",
        order = "c",
        stack_size = 50,
        place_result = "zone-control",
    },
    {
        type = "item",
        name = "tile-scan",
        icon = "__aai-programmable-structures__/graphics/icon/tile-scan.png",
        icon_size = 32,
        flags = {},
        subgroup = "programmable-structures",
        order = "a",
        stack_size = 50,
        place_result = "tile-scan",
    },
}
data:extend{{
  type = "item",
  name = "unit-scan",
  icon = "__aai-programmable-structures__/graphics/icon/unit-scan.png",
  icon_size = 32,
  flags = {},
  subgroup = "programmable-structures",
  order = "d",
  stack_size = 50,
  place_result = "unit-scan",
}}
