require('prototypes.nuclear.overwrites')
require('prototypes.nuclear.technologies-overwrite')
require('prototypes.integrations.updates')
require('prototypes.integrations.bob_thorium')
require('prototypes.integrations.bob_deuterium')