require('prototypes.integrations.items')
require('prototypes.integrations.categories')
require('prototypes.integrations.technologies')
require('prototypes.integrations.recipes')
require('prototypes.integrations.disable')
require('prototypes.integrations.fuel_categories')
require('prototypes.integrations.final-overwrites')