local technologies_icons = {
	advanced_electronics = {
		{"advanced-electronics", "advanced-electronics.png"},
		{"advanced-electronics-2", "advanced-electronics-2.png"},
		{"advanced-electronics-3", "advanced-electronics-3.png"}
	},
	advanced_material_processing = {
		{"advanced-material-processing", "advanced-material-processing.png"},
		{"advanced-material-processing-2", "advanced-material-processing-2.png"},
		{"advanced-material-processing-3", "advanced-material-processing-3.png"},
		{"advanced-material-processing-4", "advanced-material-processing-4.png"}
	},
	pumpjacks = {
		{"pumpjack", "oil.png"},
		{"bob-pumpjacks-1", "bob-pumpjacks-1.png"},
		{"bob-pumpjacks-2", "bob-pumpjacks-2.png"},
		{"bob-pumpjacks-3", "bob-pumpjacks-3.png"},
		{"bob-pumpjacks-4", "bob-pumpjacks-4.png"}
	},
	water_miner = {
		{"water-miner-1", "water-miner-1.png"},
		{"water-miner-2", "water-miner-2.png"},
		{"water-miner-3", "water-miner-3.png"},
		{"water-miner-4", "water-miner-4.png"},
		{"water-miner-5", "water-miner-5.png"}
	},
	water_bore = {
		{"water-bore-1", "water-bore-1.png"},
		{"water-bore-2", "water-bore-2.png"},
		{"water-bore-3", "water-bore-3.png"},
		{"water-bore-4", "water-bore-4.png"}
	},
	oil_processing = {
		{"oil-processing", "oil-processing-1.png"},
		{"oil-processing-2", "oil-processing-2.png"},
		{"oil-processing-3", "oil-processing-3.png"},
		{"oil-processing-4", "oil-processing-4.png"},
		{"advanced-oil-processing", "advanced-oil-processing.png"},
		{"coal-liquefaction", "coal-liquefaction.png"}
	},
	advanced_research = {
		{"advanced-research", "advanced-research.png"}
	},
	advanced_steam_power = {
		{"advanced-steam-power-1", "advanced-steam-power-1.png"},
		{"advanced-steam-power-2", "advanced-steam-power-2.png"}
	},
	air_compressor = {
		{"air-compressor-1", "air-compressor-1.png"},
		{"air-compressor-2", "air-compressor-2.png"},
		{"air-compressor-3", "air-compressor-3.png"},
		{"air-compressor-4", "air-compressor-4.png"}
	},
	alien_research = {
		{"alien-research", "alien-research.png"},
		{"alien-blue-research", "alien-blue-research.png"},
		{"alien-orange-research", "alien-orange-research.png"},
		{"alien-green-research", "alien-green-research.png"},
		{"alien-purple-research", "alien-purple-research.png"},
		{"alien-red-research", "alien-red-research.png"},
		{"alien-yellow-research", "alien-yellow-research.png"}
	},
	plates_processing = {
		{"alloy-processing-1", "alloy-processing-1.png"},
		{"alloy-processing-2", "alloy-processing-2.png"},
		{"mixing-steel-furnace", "mixing-steel-furnace.png"},
		{"multi-purpose-furnace-1", "multi-purpose-furnace-1.png"},
		{"multi-purpose-furnace-2", "multi-purpose-furnace-2.png"},
		-- {"concrete", "concrete.png"},
		{"cobalt-processing", "cobalt-processing.png"},
		{"aluminium-processing", "aluminium-processing.png"},
		{"ceramics", "ceramics.png"},
		{"cordite-processing", "cordite-processing.png"},
		{"electrum-processing", "electrum-processing.png"},
		{"gold-processing", "gold-processing.png"},
		{"heat-shield", "heat-shield.png"},
		{"invar-processing", "invar-processing.png"},
		{"lead-processing", "lead-processing.png"},
		{"lithium-processing", "lithium-processing.png"},
		{"zinc-processing", "zinc-processing.png"},
		{"nickel-processing", "nickel-processing.png"},
		{"nitinol-processing", "nitinol-processing.png"},
		{"nitrogen-processing", "nitrogen-processing.png", 64},
		{"nitroglycerin-processing", "nitroglycerin-processing.png", 64},
		{"steel-processing", "steel-processing.png"},
		{"sulfur-processing", "sulfur-processing.png"},
		{"titanium-processing", "titanium-processing.png"},
		{"tungsten-alloy-processing", "tungsten-alloy-processing.png"},
		{"tungsten-processing", "tungsten-processing.png"},
		{"silicon-processing", "silicon-processing.png"}
		-- {"hydrazine", "hydrazine.png"}
	},
	automation = {
		{"automation", "automation.png"},
		{"automation-2", "automation-2.png"},
		{"automation-3", "automation-3.png"},
		{"automation-4", "automation-4.png"},
		{"automation-5", "automation-5.png"},
		{"automation-6", "automation-6.png"}
	},
	electronics_machine = {
		{"electronics-machine-1", "electronics-machine-1.png"},
		{"electronics-machine-2", "electronics-machine-2.png"},
		{"electronics-machine-3", "electronics-machine-3.png"}
	},
	battery = {
		{"battery", "battery-1.png"},
		{"battery-2", "battery-2.png"},
		{"battery-3", "battery-3.png"}
	},
	---------   WAREFAR		     -----------
	military = {
		{"military", "military-1.png"},
		{"military-2", "military-2.png"},
		{"military-3", "military-3.png"},
		{"military-4", "military-4.png"}
	},
	tanks = {
		{"tanks", "tanks-1.png"},
		{"bob-tanks-2", "tanks-2.png"},
		{"bob-tanks-3", "tanks-3.png"}
	},
	grenade = {},
	bullets = {
		{"bob-acid-bullets", "bob-acid-bullet-magazine.png"},
		{"bob-ap-bullets", "bob-ap-bullet-magazine.png"},
		{"bob-bullets", "bob-bullet-magazine.png"},
		{"bob-electric-bullets", "bob-electric-bullet-magazine.png"},
		{"bob-flame-bullets", "bob-flame-bullet-magazine.png"},
		{"bob-he-bullets", "bob-he-bullet-magazine.png"},
		{"bob-poison-bullets", "bob-poison-bullet-magazine.png"},
		{"bullet-damage-1", "bullet-damage.png"},
		{"bullet-damage-2", "bullet-damage.png"},
		{"bullet-damage-3", "bullet-damage.png"},
		{"bullet-damage-4", "bullet-damage.png"},
		{"bullet-damage-5", "bullet-damage.png"},
		{"bullet-damage-6", "bullet-damage.png"},
		{"bullet-damage-7", "bullet-damage.png"},
		{"bullet-speed-1", "bullet-speed.png"},
		{"bullet-speed-2", "bullet-speed.png"},
		{"bullet-speed-3", "bullet-speed.png"},
		{"bullet-speed-4", "bullet-speed.png"},
		{"bullet-speed-5", "bullet-speed.png"},
		{"bullet-speed-6", "bullet-speed.png"}
	},
	rockets = {
		{"bob-acid-rocket", "bob-acid-rocket.png"},
		{"bob-electric-rocket", "bob-electric-rocket.png"},
		{"bob-explosive-rocket", "bob-explosive-rocket.png"},
		{"bob-flame-rocket", "bob-flame-rocket.png"},
		{"bob-piercing-rocket", "bob-piercing-rocket.png"},
		{"bob-poison-rocket", "bob-poison-rocket.png"},
		{"bob-rocket", "bob-rocket.png"},
		{"rocketry", "rocketry.png"},
		{"atomic-bomb", "atomic-bomb.png"},
		{"rocket-damage-1", "rocket-damage.png"},
		{"rocket-damage-2", "rocket-damage.png"},
		{"rocket-damage-3", "rocket-damage.png"},
		{"rocket-damage-4", "rocket-damage.png"},
		{"rocket-damage-5", "rocket-damage.png"},
		{"rocket-damage-6", "rocket-damage.png"},
		{"rocket-damage-7", "rocket-damage.png"},
		{"rocket-speed-1", "rocket-speed.png"},
		{"rocket-speed-2", "rocket-speed.png"},
		{"rocket-speed-3", "rocket-speed.png"},
		{"rocket-speed-4", "rocket-speed.png"},
		{"rocket-speed-5", "rocket-speed.png"},
		{"rocket-speed-6", "rocket-speed.png"},
		{"rocket-speed-7", "rocket-speed.png"}
	},
	shotgun_shells = {
		{"bob-shotgun-acid-shells", "bob-shotgun-acid-shell.png"},
		{"bob-shotgun-ap-shells", "bob-shotgun-ap-shell.png"},
		{"bob-shotgun-electric-shells", "bob-shotgun-electric-shell.png"},
		{"bob-shotgun-explosive-shells", "bob-shotgun-explosive-shell.png"},
		{"bob-shotgun-flame-shells", "bob-shotgun-flame-shell.png"},
		{"bob-shotgun-poison-shells", "bob-shotgun-poison-shell.png"},
		{"bob-shotgun-shells", "bob-shotgun-shell.png"},
		{"shotgun-shell-damage-1", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-2", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-3", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-4", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-5", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-6", "shotgun-shell-damage.png"},
		{"shotgun-shell-damage-7", "shotgun-shell-damage.png"},
		{"shotgun-shell-speed-1", "shotgun-shell-speed.png"},
		{"shotgun-shell-speed-2", "shotgun-shell-speed.png"},
		{"shotgun-shell-speed-3", "shotgun-shell-speed.png"},
		{"shotgun-shell-speed-4", "shotgun-shell-speed.png"},
		{"shotgun-shell-speed-5", "shotgun-shell-speed.png"},
		{"shotgun-shell-speed-6", "shotgun-shell-speed.png"}
	},
	laser_rifle = {
		{"bob-laser-rifle", "laser-rifle.png", 64},
		{"bob-laser-rifle-ammo-1", "laser-rifle-ammo-1.png", 64},
		{"bob-laser-rifle-ammo-2", "laser-rifle-ammo-2.png", 64},
		{"bob-laser-rifle-ammo-3", "laser-rifle-ammo-3.png", 64},
		{"bob-laser-rifle-ammo-4", "laser-rifle-ammo-4.png", 64},
		{"bob-laser-rifle-ammo-5", "laser-rifle-ammo-5.png", 64},
		{"bob-laser-rifle-ammo-6", "laser-rifle-ammo-6.png", 64},
		{"bob-laser-rifle-damage-1", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-2", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-3", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-4", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-5", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-6", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-damage-7", "laser-rifle-damage.png", 64},
		{"bob-laser-rifle-speed-1", "laser-rifle-speed.png", 64},
		{"bob-laser-rifle-speed-2", "laser-rifle-speed.png", 64},
		{"bob-laser-rifle-speed-3", "laser-rifle-speed.png", 64},
		{"bob-laser-rifle-speed-4", "laser-rifle-speed.png", 64},
		{"bob-laser-rifle-speed-5", "laser-rifle-speed.png", 64},
		{"bob-laser-rifle-speed-6", "laser-rifle-speed.png", 64}
	},
	turrets = {
		{"turrets", "gun-turrets-1.png"},
		{"bob-turrets-2", "gun-turrets-2.png"},
		{"bob-turrets-3", "gun-turrets-3.png"},
		{"bob-turrets-4", "gun-turrets-4.png"},
		{"bob-turrets-5", "gun-turrets-5.png"},
		{"gun-turret-damage-1", "gun-turret-damage.png"},
		{"gun-turret-damage-2", "gun-turret-damage.png"},
		{"gun-turret-damage-3", "gun-turret-damage.png"},
		{"gun-turret-damage-4", "gun-turret-damage.png"},
		{"gun-turret-damage-5", "gun-turret-damage.png"},
		{"gun-turret-damage-6", "gun-turret-damage.png"},
		{"gun-turret-damage-7", "gun-turret-damage.png"}
	},
	sniper_turrets = {
		{"bob-sniper-turrets-1", "sniper-turrets-1.png"},
		{"bob-sniper-turrets-2", "sniper-turrets-2.png"},
		{"bob-sniper-turrets-3", "sniper-turrets-3.png"},
		{"bob-sniper-turret-damage-1", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-2", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-3", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-4", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-5", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-6", "sniper-turrets-damage.png"},
		{"bob-sniper-turret-damage-7", "sniper-turrets-damage.png"}
	},
	laser_turrets = {
		{"laser-turrets", "laser-turrets-1.png"},
		{"bob-laser-turrets-2", "laser-turrets-2.png"},
		{"bob-laser-turrets-3", "laser-turrets-3.png"},
		{"bob-laser-turrets-4", "laser-turrets-4.png"},
		{"bob-laser-turrets-5", "laser-turrets-5.png"},
		{"laser-turret-damage-1", "laser-turret-damage.png"},
		{"laser-turret-damage-2", "laser-turret-damage.png"},
		{"laser-turret-damage-3", "laser-turret-damage.png"},
		{"laser-turret-damage-4", "laser-turret-damage.png"},
		{"laser-turret-damage-5", "laser-turret-damage.png"},
		{"laser-turret-damage-6", "laser-turret-damage.png"},
		{"laser-turret-damage-7", "laser-turret-damage.png"},
		{"laser-turret-damage-8", "laser-turret-damage.png"},
		{"laser-turret-speed-1", "laser-turret-speed.png"},
		{"laser-turret-speed-2", "laser-turret-speed.png"},
		{"laser-turret-speed-3", "laser-turret-speed.png"},
		{"laser-turret-speed-4", "laser-turret-speed.png"},
		{"laser-turret-speed-5", "laser-turret-speed.png"},
		{"laser-turret-speed-6", "laser-turret-speed.png"},
		{"laser-turret-speed-7", "laser-turret-speed.png"}
	},
	artillery = {
		{"artillery", "artillery-turret-1.png"},
		{"bob-artillery-turret-2", "artillery-turret-2.png"},
		{"bob-artillery-turret-3", "artillery-turret-3.png"},
		{"artillery-shell-range-1", "artillery-range.png"},
		{"artillery-shell-speed-1", "artillery-speed.png"},
		{"bob-artillery-wagon-2", "artillery-wagon-2.png"},
		{"bob-artillery-wagon-3", "artillery-wagon-3.png"},
		{"bob-artillery-damage-1", "artillery-damage.png"},
		{"bob-artillery-damage-2", "artillery-damage.png"},
		{"bob-artillery-damage-3", "artillery-damage.png"},
		{"bob-artillery-damage-4", "artillery-damage.png"},
		{"bob-artillery-damage-5", "artillery-damage.png"},
		{"bob-artillery-damage-6", "artillery-damage.png"},
		{"cannon-shell-damage-1", "cannon-damage.png"},
		{"cannon-shell-damage-2", "cannon-damage.png"},
		{"cannon-shell-damage-3", "cannon-damage.png"},
		{"cannon-shell-damage-4", "cannon-damage.png"},
		{"cannon-shell-damage-5", "cannon-damage.png"},
		{"cannon-shell-damage-6", "cannon-damage.png"},
		{"cannon-shell-speed-1", "cannon-speed.png"},
		{"cannon-shell-speed-2", "cannon-speed.png"},
		{"cannon-shell-speed-3", "cannon-speed.png"},
		{"cannon-shell-speed-4", "cannon-speed.png"},
		{"cannon-shell-speed-5", "cannon-speed.png"}
	},
	flamethrower = {},
	mines = {
		{"land-mine", "land-mine.png"},
		{"distractor-mine", "land-mine-distractor.png"},
		{"poison-mine", "land-mine-poison.png"},
		{"slowdown-mine", "land-mine-slowdown.png"}
	},
	armors = {
		{"modular-armor", "armor-making.png"},
		{"bob-armor-making-3", "armor-making-3.png"},
		{"bob-armor-making-4", "armor-making-4.png"},
		--   {"heavy-armor","heavy-armor.png"},

		{"power-armor", "power-armor.png"},
		{"power-armor-2", "power-armor-mk2.png"},
		{"bob-power-armor-3", "power-armor-mk3.png", 64},
		{"bob-power-armor-4", "power-armor-mk4.png", 64},
		{"bob-power-armor-5", "power-armor-mk5.png", 64}
	},
	-----------------------

	drills = {
		{"bob-drills-1", "mining-drill-1.png"},
		{"bob-drills-2", "mining-drill-2.png"},
		{"bob-drills-3", "mining-drill-3.png"},
		{"bob-drills-4", "mining-drill-4.png"},
		{"bob-area-drills-1", "mining-drill-area-1.png"},
		{"bob-area-drills-2", "mining-drill-area-2.png"},
		{"bob-area-drills-3", "mining-drill-area-3.png"},
		{"bob-area-drills-4", "mining-drill-area-4.png"},
		{"mining-productivity-1", "mining-productivity.png"},
		{"mining-productivity-4", "mining-productivity.png"},
		{"mining-productivity-8", "mining-productivity.png"},
		{"mining-productivity-12", "mining-productivity.png"},
		{"mining-productivity-16", "mining-productivity.png"}
	},
	wagons = {
		{"fluid-wagon", "fluid-wagon-1.png"},
		{"bob-fluid-wagon-2", "fluid-wagon-2.png"},
		{"bob-fluid-wagon-3", "fluid-wagon-3.png"},
		{"bob-armoured-fluid-wagon", "fluid-wagon-armoured-1.png"},
		{"bob-armoured-fluid-wagon-2", "fluid-wagon-armoured-2.png"}
	},
	railway = {
		{"railway", "railway-1.png"},
		{"bob-railway-2", "railway-2.png"},
		{"bob-railway-3", "railway-3.png"},
		{"bob-armoured-railway", "railway-armoured-1.png"},
		{"bob-armoured-railway-2", "railway-armoured-2.png"}
	},
	boilers = {
		{"bob-boiler-1", "boiler-2.png"},
		{"bob-boiler-2", "boiler-3.png"},
		{"bob-boiler-3", "boiler-4.png"}
	},
	accumulators = {
		{"electric-energy-accumulators-1", "electric-energy-accumulators-0.png"},
		{"bob-electric-energy-accumulators-2", "electric-energy-accumulators-1.png"},
		{"bob-electric-energy-accumulators-3", "electric-energy-accumulators-2.png"},
		{"bob-electric-energy-accumulators-4", "electric-energy-accumulators-3.png"}
	},
	greenhouse = {
		{"bob-greenhouse", "greenhouse.png"},
		{"bob-fertiliser", "fertiliser.png"}
	},
	fluid_handling = {
		{"fluid-handling", "fluid-handling-1.png"},
		{"bob-fluid-handling-2", "fluid-handling-2.png"},
		{"bob-fluid-handling-3", "fluid-handling-3.png"},
		{"bob-fluid-handling-4", "fluid-handling-4.png"}
	},
	logistics = {
		{"logistics", "logistics-1.png"},
		{"logistics-2", "logistics-2.png"},
		{"logistics-3", "logistics-3.png"},
		{"bob-logistics-4", "logistics-4.png"},
		{"bob-logistics-5", "logistics-5.png"}
	},
	robotics = {
		{"bob-robo-modular-1", "roboport-1.png"},
		{"bob-robo-modular-2", "roboport-2.png"},
		{"bob-robo-modular-3", "roboport-3.png"},
		{"bob-robo-modular-4", "roboport-4.png"},
		{"bob-robot-tanks", "drone-tanks.png"},
		{"construction-robotics", "construction-robotics.png"},
		{"logistic-robotics", "logistic-robotics.png"},
		{"robotics", "robotics-1.png"},
		{"bob-robotics-2", "robotics-2.png"},
		{"bob-robotics-3", "robotics-3.png"},
		{"bob-robotics-4", "robotics-4.png"},
		{"bob-robotics-5", "robotics-5.png"},
		{"bob-robots-1", "bob-robots-2.png"},
		{"bob-robots-2", "bob-robots-3.png"},
		{"bob-robots-3", "bob-robots-4.png"},
		{"bob-robots-4", "bob-robots-5.png"},
		-- {"worker-robots-speed-1", "worker-robots-speed-1.png"},
		-- {"worker-robots-speed-2", "worker-robots-speed-2.png"},
		-- {"worker-robots-speed-3", "worker-robots-speed-3.png"},
		-- {"worker-robots-speed-4", "worker-robots-speed-4.png"},
		-- {"worker-robots-speed-5", "worker-robots-speed-5.png"},
		-- {"worker-robots-speed-6", "worker-robots-speed-6.png"},
		-- {"worker-robots-storage-1", "worker-robots-storage-1.png"},
		-- {"worker-robots-storage-2", "worker-robots-storage-2.png"},
		-- {"worker-robots-storage-3", "worker-robots-storage-3.png"},
		-- {"worker-robots-storage-4", "worker-robots-storage-4.png"},
		-- {"worker-robots-storage-5", "worker-robots-storage-5.png"},
		-- {"worker-robots-storage-6", "worker-robots-storage-6.png"},
		-- {"worker-robots-storage-7", "worker-robots-storage-7.png"},
		-- {"worker-robots-storage-8", "worker-robots-storage-8.png"},
		-- {"worker-robots-storage-9", "worker-robots-storage-9.png"},
		-- {"worker-robots-storage-10", "worker-robots-storage-10.png"},
		{"combat-robotics", "combat-robotics-1.png"},
		{"combat-robotics-2", "combat-robotics-2.png"},
		{"combat-robotics-3", "combat-robotics-3.png"},
		{"combat-robotics-4", "combat-robotics-4.png"}
		-- {"combat-robot-damage-1", "combat-robot-damage-1.png"},
		-- {"combat-robot-damage-2", "combat-robot-damage-2.png"},
		-- {"combat-robot-damage-3", "combat-robot-damage-3.png"},
		-- {"combat-robot-damage-4", "combat-robot-damage-4.png"},
		-- {"combat-robot-damage-5", "combat-robot-damage-5.png"},
		-- {"combat-robot-damage-6", "combat-robot-damage-6.png"},
		-- {"follower-robot-count-1", "follower-robot-count-1.png"},
		-- {"follower-robot-count-2", "follower-robot-count-2.png"},
		-- {"follower-robot-count-3", "follower-robot-count-3.png"},
		-- {"follower-robot-count-4", "follower-robot-count-4.png"},
		-- {"follower-robot-count-5", "follower-robot-count-5.png"},
		-- {"follower-robot-count-6", "follower-robot-count-6.png"},
		-- {"follower-robot-count-7", "follower-robot-count-7.png"}
	},
	solar = {
		{"solar-energy", "solar-energy-1.png"},
		{"bob-solar-energy-2", "solar-energy-2.png"},
		{"bob-solar-energy-3", "solar-energy-3.png"},
		{"bob-solar-energy-4", "solar-energy-4.png"}
	},
	braking = {},
	inventory = {
		{"toolbelt", "toolbelt-1.png"},
		{"toolbelt-2", "toolbelt-2.png"},
		{"toolbelt-3", "toolbelt-3.png"}
		-- {"character-inventory-slots-1", "character-inventory-slots-1.png"},
		-- {"character-inventory-slots-2", "character-inventory-slots-2.png"},
		-- {"character-inventory-slots-3", "character-inventory-slots-3.png"},
		-- {"character-inventory-slots-4", "character-inventory-slots-4.png"},
		-- {"character-logistic-slots-1", "character-logistic-slots-1.png"},
		-- {"character-logistic-slots-2", "character-logistic-slots-2.png"},
		-- {"character-logistic-slots-3", "character-logistic-slots-3.png"},
		-- {"character-logistic-slots-4", "character-logistic-slots-4.png"},
		-- {"character-logistic-slots-5", "character-logistic-slots-5.png"},
		-- {"character-logistic-slots-6", "character-logistic-slots-6.png"},
		-- {"character-logistic-slots-7", "character-logistic-slots-7.png"},
		-- {"character-logistic-slots-8", "character-logistic-slots-8.png"},
		-- {"character-logistic-slots-9", "character-logistic-slots-9.png"},
		-- {"character-logistic-slots-10", "character-logistic-slots-10.png"},
		-- {"character-logistic-trash-slots-1", "character-logistic-trash-slots-1.png"},
		-- {"character-logistic-trash-slots-2", "character-logistic-trash-slots-2.png"},
		-- {"character-logistic-trash-slots-3", "character-logistic-trash-slots-3.png"},
		-- {"character-logistic-trash-slots-4", "character-logistic-trash-slots-4.png"},
		-- {"inventory-size", "inventory-size.png"},
		-- {"inventory-size-2", "inventory-size-2.png"},
		-- {"inventory-size-3", "inventory-size-3.png"},
		-- {"inventory-size-4", "inventory-size-4.png"},
		-- {"inventory-size-5", "inventory-size-5.png"}
	},
	chemical_plant = {
		{"chemical-plant", "chemical-plant-1.png"},
		{"chemical-plant-2", "chemical-plant-2.png"},
		{"chemical-plant-3", "chemical-plant-3.png"},
		{"chemical-plant-4", "chemical-plant-4.png"}
	},
	chemical_processing = {
		{"chemical-processing-1", "chemical-processing-1.png"},
		{"chemical-processing-2", "chemical-processing-2.png"},
		{"chemical-processing-3", "chemical-processing-3.png"}
	},
	crafting = {},
	effect_transmission = {
		{"effect-transmission", "effect-transmission-1.png"},
		{"effect-transmission-2", "effect-transmission-2.png"},
		{"effect-transmission-3", "effect-transmission-3.png"}
	},
	electric_energy = {
		{"electric-energy-distribution-1", "electric-pole-1.png"},
		{"electric-pole-2", "electric-pole-2.png"},
		{"electric-pole-3", "electric-pole-3.png"},
		{"electric-pole-4", "electric-pole-4.png"},
		{"electric-energy-distribution-2", "electric-substation-1.png"},
		{"electric-substation-2", "electric-substation-2.png"},
		{"electric-substation-3", "electric-substation-3.png"},
		{"electric-substation-4", "electric-substation-4.png"}
	},
	modules = {
		{"modules", "modules-1.png"},
		{"module-merging", "modules-2.png"},
		{"effectivity-module", "modules/effectivity-module-1.png"},
		{"effectivity-module-2", "modules/effectivity-module-2.png"},
		{"effectivity-module-3", "modules/effectivity-module-3.png"},
		{"effectivity-module-4", "modules/effectivity-module-4.png"},
		{"effectivity-module-5", "modules/effectivity-module-5.png"},
		{"effectivity-module-6", "modules/effectivity-module-6.png"},
		{"effectivity-module-7", "modules/effectivity-module-7.png"},
		{"effectivity-module-8", "modules/effectivity-module-8.png"},
		{"productivity-module", "modules/productivity-module-1.png"},
		{"productivity-module-2", "modules/productivity-module-2.png"},
		{"productivity-module-3", "modules/productivity-module-3.png"},
		{"productivity-module-4", "modules/productivity-module-4.png"},
		{"productivity-module-5", "modules/productivity-module-5.png"},
		{"productivity-module-6", "modules/productivity-module-6.png"},
		{"productivity-module-7", "modules/productivity-module-7.png"},
		{"productivity-module-8", "modules/productivity-module-8.png"},
		{"speed-module", "modules/speed-module-1.png"},
		{"speed-module-2", "modules/speed-module-2.png"},
		{"speed-module-3", "modules/speed-module-3.png"},
		{"speed-module-4", "modules/speed-module-4.png"},
		{"speed-module-5", "modules/speed-module-5.png"},
		{"speed-module-6", "modules/speed-module-6.png"},
		{"speed-module-7", "modules/speed-module-7.png"},
		{"speed-module-8", "modules/speed-module-8.png"},
		{"pollution-clean-module-1", "modules/pollution-clean-module-1.png"},
		{"pollution-clean-module-2", "modules/pollution-clean-module-2.png"},
		{"pollution-clean-module-3", "modules/pollution-clean-module-3.png"},
		{"pollution-clean-module-4", "modules/pollution-clean-module-4.png"},
		{"pollution-clean-module-5", "modules/pollution-clean-module-5.png"},
		{"pollution-clean-module-6", "modules/pollution-clean-module-6.png"},
		{"pollution-clean-module-7", "modules/pollution-clean-module-7.png"},
		{"pollution-clean-module-8", "modules/pollution-clean-module-8.png"},
		{"pollution-create-module-1", "modules/pollution-create-module-1.png"},
		{"pollution-create-module-2", "modules/pollution-create-module-2.png"},
		{"pollution-create-module-3", "modules/pollution-create-module-3.png"},
		{"pollution-create-module-4", "modules/pollution-create-module-4.png"},
		{"pollution-create-module-5", "modules/pollution-create-module-5.png"},
		{"pollution-create-module-6", "modules/pollution-create-module-6.png"},
		{"pollution-create-module-7", "modules/pollution-create-module-7.png"},
		{"pollution-create-module-8", "modules/pollution-create-module-8.png"},
		{"raw-productivity-module-1", "modules/red-module-1.png"},
		{"raw-productivity-module-2", "modules/red-module-2.png"},
		{"raw-productivity-module-3", "modules/red-module-3.png"},
		{"raw-productivity-module-4", "modules/red-module-4.png"},
		{"raw-productivity-module-5", "modules/red-module-5.png"},
		{"raw-productivity-module-6", "modules/red-module-6.png"},
		{"raw-productivity-module-7", "modules/red-module-7.png"},
		{"raw-productivity-module-8", "modules/red-module-8.png"},
		{"green-module-1", "modules/yellow-module-1.png"},
		{"green-module-2", "modules/yellow-module-2.png"},
		{"green-module-3", "modules/yellow-module-3.png"},
		{"green-module-4", "modules/yellow-module-4.png"},
		{"green-module-5", "modules/yellow-module-5.png"},
		{"green-module-6", "modules/yellow-module-6.png"},
		{"green-module-7", "modules/yellow-module-7.png"},
		{"green-module-8", "modules/yellow-module-8.png"},
		{"raw-speed-module-1", "modules/cyan-module-1.png"},
		{"raw-speed-module-2", "modules/cyan-module-2.png"},
		{"raw-speed-module-3", "modules/cyan-module-3.png"},
		{"raw-speed-module-4", "modules/cyan-module-4.png"},
		{"raw-speed-module-5", "modules/cyan-module-5.png"},
		{"raw-speed-module-6", "modules/cyan-module-6.png"},
		{"raw-speed-module-7", "modules/cyan-module-7.png"},
		{"raw-speed-module-8", "modules/cyan-module-8.png"},
		{"god-module-1", "modules/god-module-1.png"},
		{"god-module-2", "modules/god-module-2.png"},
		{"god-module-3", "modules/god-module-3.png"},
		{"god-module-4", "modules/god-module-4.png"},
		{"god-module-5", "modules/god-module-5.png"}
	},
	engine = {
		{"engine", "engine.png"},
		{"electric-engine", "electric-engine.png"}
	},
	electrolysis = {
		{"electrolysis-1", "electrolysis-1.png"},
		{"electrolysis-2", "electrolysis-2.png"}
	},
	electrolyser = {
		{"electrolyser-2", "electrolyser-2.png"},
		{"electrolyser-3", "electrolyser-3.png"},
		{"electrolyser-4", "electrolyser-4.png"}
	},
	inserters = {
		{"long-inserters-1", "long-inserters-1.png"},
		{"long-inserters-2", "long-inserters-2.png"},
		{"more-inserters-1", "more-inserters-1.png"},
		{"more-inserters-2", "more-inserters-2.png"},
		{"near-inserters", "near-inserters.png"},
		{"express-inserters", "express-inserters.png"},
		{"stack-inserter", "stack-inserters.png"},
		{"stack-inserter-2", "stack-inserters-2.png"},
		{"inserter-capacity-bonus-1", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-2", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-3", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-4", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-5", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-6", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-7", "inserter-capacity-bonus.png"},
		{"inserter-capacity-bonus-8", "inserter-capacity-bonus.png"},
		{"inserter-stack-size-bonus-1", "stack-inserter-capacity-bonus.png"},
		{"inserter-stack-size-bonus-2", "stack-inserter-capacity-bonus.png"},
		{"inserter-stack-size-bonus-3", "stack-inserter-capacity-bonus.png"},
		{"inserter-stack-size-bonus-4", "stack-inserter-capacity-bonus.png"}
	},
	logistic_system = {},
	research_speed = {},
	other = {
		{"void-fluid", "void.png"},
		-- {"automobilism","automobilism.png"},
		-- {"auto-character-logistic-trash-slots", "auto-character-logistic-trash-slots.png"},
		-- {"auto-targeting","auto-targeting.png"},
		-- {"automated-rail-transportation", "automated-rail-transportation.png"},
		-- {"circuit-network","circuit-network.png"},
		-- {"electronics","electronics.png"},
		-- {"explosives","explosives.png"},
		-- {"cliff-explosives","cliff-explosives.png"},
		-- {"flying",	"flying.png"},
		-- {"gas-canisters","gas-canisters.png"},
		-- {"stone-walls","stone-walls.png"},
		-- {"gates", "gates.png"},
		{"reinforced-wall", "reinforced-wall.png"},
		{"gem-processing-1", "gem-processing-1.png"},
		{"gem-processing-2", "gem-processing-2.png"},
		{"grinding", "grinding.png", 64},
		-- {"kovarex-enrichment-process", "kovarex-enrichment-process.png"},
		-- {"landfill","landfill.png"},
		-- {"flammables","flammables.png"},
		-- {"nuclear-fuel-reprocessing", 	"nuclear-fuel-reprocessing.png"},
		-- {"nuclear-power","nuclear-power.png"},
		-- {"uranium-ammo","uranium-ammo.png"},
		-- {"laser", "laser.png"},
		-- {"explosive-rocketry", "explosive-rocketry.png"},
		-- {"optics",	"optics.png"},
		-- {"plastics","plastics.png"},
		-- {"polishing","polishing.png"},
		-- {"rail-signals","rail-signals.png"},
		{"rocket-fuel", "rocket-fuel.png"},
		{"solid-fuel", "solid-fuel.png"},
		-- {"rocket-silo","rocket-silo.png"},
		{"low-density-structure", "low-density-structure.png"}
	},
	steam_engine = {
		{"steam-engine-generator-1", "steam-engine-2.png"},
		{"steam-engine-generator-2", "steam-engine-3.png"}
	},
	fluidgenerator = {
		{"fluid-generator-1", "fluid-generator-1.png"},
		{"fluid-generator-2", "fluid-generator-2.png"},
		{"fluid-generator-3", "fluid-generator-3.png"},
		{"hydrazine-generator", "fluid-generator-4.png"}
	},
	radars = {
		{"radars", "radars-2.png"},
		{"radars-2", "radars-2.png"},
		{"radars-3", "radars-4.png"},
		{"radars-4", "radars-5.png"}
	},
	equipment = {
		{"solar-panel-equipment", "solar-panel-equipment-1.png"},
		{"solar-panel-equipment-2", "solar-panel-equipment-2.png"},
		{"solar-panel-equipment-3", "solar-panel-equipment-3.png"},
		{"solar-panel-equipment-4", "solar-panel-equipment-4.png"},
		{"personal-laser-defense-equipment", "personal-laser-defense-equipment-1.png"},
		{"personal-laser-defense-equipment-2", "personal-laser-defense-equipment-2.png"},
		{"personal-laser-defense-equipment-3", "personal-laser-defense-equipment-3.png"},
		{"personal-laser-defense-equipment-4", "personal-laser-defense-equipment-4.png"},
		{"personal-laser-defense-equipment-5", "personal-laser-defense-equipment-5.png"},
		{"personal-laser-defense-equipment-6", "personal-laser-defense-equipment-6.png"},
		{"personal-roboport-equipment", "personal-roboport-equipment-1.png"},
		{"personal-roboport-equipment-2", "personal-roboport-equipment-2.png"},
		{"battery-equipment", "battery-equipment-1.png"},
		{"battery-mk2-equipment", "battery-equipment-2.png"},
		{"battery-equipment-3", "battery-equipment-3.png"},
		{"battery-equipment-4", "battery-equipment-4.png"},
		{"battery-equipment-5", "battery-equipment-5.png"},
		{"battery-equipment-6", "battery-equipment-6.png"},
		{"energy-shield-equipment", "energy-shield-equipment-1.png"},
		{"energy-shield-mk2-equipment", "energy-shield-equipment-2.png"},
		{"energy-shield-equipment-3", "energy-shield-equipment-3.png"},
		{"energy-shield-equipment-4", "energy-shield-equipment-4.png"},
		{"energy-shield-equipment-5", "energy-shield-equipment-5.png"},
		{"energy-shield-equipment-6", "energy-shield-equipment-6.png"},
		{"exoskeleton-equipment", "exoskeleton-equipment-1.png"},
		{"exoskeleton-equipment-2", "exoskeleton-equipment-2.png"},
		{"exoskeleton-equipment-3", "exoskeleton-equipment-3.png"},
		{"fusion-reactor-equipment", "fusion-reactor-equipment-1.png"},
		{"fusion-reactor-equipment-2", "fusion-reactor-equipment-2.png"},
		{"fusion-reactor-equipment-3", "fusion-reactor-equipment-3.png"},
		{"fusion-reactor-equipment-4", "fusion-reactor-equipment-4.png"},
		{"night-vision-equipment", "night-vision-equipment-1.png"},
		{"night-vision-equipment-2", "night-vision-equipment-2.png"},
		{"night-vision-equipment-3", "night-vision-equipment-3.png"},
		{"discharge-defense-equipment", "discharge-defense-equipment.png"}
	},
	vehicle_equipment = {
		{"vehicle-battery-equipment-1", "vehicle-battery-equipment-1.png"},
		{"vehicle-battery-equipment-2", "vehicle-battery-equipment-2.png"},
		{"vehicle-battery-equipment-3", "vehicle-battery-equipment-3.png"},
		{"vehicle-battery-equipment-4", "vehicle-battery-equipment-4.png"},
		{"vehicle-battery-equipment-5", "vehicle-battery-equipment-5.png"},
		{"vehicle-battery-equipment-6", "vehicle-battery-equipment-6.png"},
		{"vehicle-big-turret-equipment-1", "vehicle-big-turret-equipment-1.png"},
		{"vehicle-big-turret-equipment-2", "vehicle-big-turret-equipment-2.png"},
		{"vehicle-big-turret-equipment-3", "vehicle-big-turret-equipment-3.png"},
		{"vehicle-big-turret-equipment-4", "vehicle-big-turret-equipment-4.png"},
		{"vehicle-big-turret-equipment-5", "vehicle-big-turret-equipment-5.png"},
		{"vehicle-big-turret-equipment-6", "vehicle-big-turret-equipment-6.png"},
		{"vehicle-energy-shield-equipment-1", "vehicle-energy-shield-equipment-1.png", 64},
		{"vehicle-energy-shield-equipment-2", "vehicle-energy-shield-equipment-2.png", 64},
		{"vehicle-energy-shield-equipment-3", "vehicle-energy-shield-equipment-3.png", 64},
		{"vehicle-energy-shield-equipment-4", "vehicle-energy-shield-equipment-4.png", 64},
		{"vehicle-energy-shield-equipment-5", "vehicle-energy-shield-equipment-5.png", 64},
		{"vehicle-energy-shield-equipment-6", "vehicle-energy-shield-equipment-6.png", 64},
		{"vehicle-fusion-cell-equipment-1", "vehicle-fusion-cell-equipment-1.png"},
		{"vehicle-fusion-cell-equipment-2", "vehicle-fusion-cell-equipment-2.png"},
		{"vehicle-fusion-cell-equipment-3", "vehicle-fusion-cell-equipment-3.png"},
		{"vehicle-fusion-cell-equipment-4", "vehicle-fusion-cell-equipment-4.png"},
		{"vehicle-fusion-cell-equipment-5", "vehicle-fusion-cell-equipment-5.png"},
		{"vehicle-fusion-cell-equipment-6", "vehicle-fusion-cell-equipment-6.png"},
		{"vehicle-fusion-reactor-equipment-1", "vehicle-fusion-reactor-equipment-1.png"},
		{"vehicle-fusion-reactor-equipment-2", "vehicle-fusion-reactor-equipment-2.png"},
		{"vehicle-fusion-reactor-equipment-3", "vehicle-fusion-reactor-equipment-3.png"},
		{"vehicle-fusion-reactor-equipment-4", "vehicle-fusion-reactor-equipment-4.png"},
		{"vehicle-fusion-reactor-equipment-5", "vehicle-fusion-reactor-equipment-5.png"},
		{"vehicle-fusion-reactor-equipment-6", "vehicle-fusion-reactor-equipment-6.png"},
		{"vehicle-laser-defense-equipment-1", "vehicle-laser-defense-equipment-1.png"},
		{"vehicle-laser-defense-equipment-2", "vehicle-laser-defense-equipment-2.png"},
		{"vehicle-laser-defense-equipment-3", "vehicle-laser-defense-equipment-3.png"},
		{"vehicle-laser-defense-equipment-4", "vehicle-laser-defense-equipment-4.png"},
		{"vehicle-laser-defense-equipment-5", "vehicle-laser-defense-equipment-5.png"},
		{"vehicle-laser-defense-equipment-6", "vehicle-laser-defense-equipment-6.png"},
		{"vehicle-engine-equipment", "vehicle-engine-equipment.png"},
		{"vehicle-motor-equipment", "vehicle-motor-equipment.png"},
		{"vehicle-roboport-equipment", "vehicle-roboport-equipment-1.png"},
		{"vehicle-roboport-equipment-2", "vehicle-roboport-equipment-2.png"},
		{"vehicle-solar-panel-equipment-1", "vehicle-solar-panel-equipment-1.png"},
		{"vehicle-solar-panel-equipment-2", "vehicle-solar-panel-equipment-2.png"},
		{"vehicle-solar-panel-equipment-3", "vehicle-solar-panel-equipment-3.png"},
		{"vehicle-solar-panel-equipment-4", "vehicle-solar-panel-equipment-4.png"},
		{"vehicle-solar-panel-equipment-5", "vehicle-solar-panel-equipment-5.png"},
		{"vehicle-solar-panel-equipment-6", "vehicle-solar-panel-equipment-6.png"}
	},
	----------- OTHER MODS

	loaders = {
		{"loader", "loader-1.png", nil, "a-f-a1"},
		{"fast-loader", "loader-2.png", nil, "a-f-b1"},
		{"express-loader", "loader-3.png", nil, "a-f-c1"},
		{"green-loader", "loader-4.png", nil, "a-f-d1"},
		{"purple-loader", "loader-5.png", nil, "a-f-e1"}
	},
	miniloaders = {
		{"miniloader", "miniloader.png", nil, "a-f-a2"},
		{"fast-miniloader", "fast-miniloader.png", nil, "a-f-b2"},
		{"express-miniloader", "express-miniloader.png", nil, "a-f-c2"},
		{"purple-miniloader", "green-miniloader.png", nil, "a-f-d2"},
		{"green-miniloader", "purple-miniloader.png", nil, "a-f-e2"}
	},
	belt_sorter = {},
	air_filtering = {},
	othermods = {
		{"better-repair-pack", "better-repair-pack.png"}
		-- {"warehouse-logistics-research", "warehouse-logistics-research.png"},
		-- {"warehouse-research", "warehouse-research.png"},
		-- {"resource-monitoring", "resource-monitoring.png"},
		-- {"reverse-factory", "reverse-factory.png"},
		-- {"shuttle-lite", "shuttle-lite.png"},
		-- {"pickstick", "pickstick.png"},
		-- {"pickstick-2", "pickstick-2.png"},
		-- {"pickstick-3", "pickstick-3.png"},
		-- {"pickstick-4", "pickstick-4.png"},
		-- {"pickstick-5", "pickstick-5.png"},
		-- {"orbital-ion-cannon", "orbital-ion-cannon.png"},
		-- {"wind-turbine", "wind-turbine.png"},
		-- {"wind-turbine2", "wind-turbine2.png"},
		-- {"wind-turbine3", "wind-turbine3.png"},
		-- {"logistic-train-network", "logistic-train-network.png"},
		-- {"roboport-interface", "roboport-interface.png"},
	},
	nanotech = {
		-- {"nanobots", "nanobots.png"},
		{"nano-range-1", "nano-range.png"},
		{"nano-range-2", "nano-range.png"},
		{"nano-range-3", "nano-range.png"},
		{"nano-range-4", "nano-range.png"},
		{"nano-speed-1", "nano-speed.png"},
		{"nano-speed-2", "nano-speed.png"},
		{"nano-speed-3", "nano-speed.png"},
		{"nano-speed-4", "nano-speed.png"}
	}
}

setall_icons(technologies_icons)
